name: Node CI
on:
  pull_request: types:[opened, edited, synchronize]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout the repo
      - run: npm install # install packages
      - run: npm test # run tests (configured to use jest-junit reporter)
